/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedProjectIdRouteImport } from './routes/_authenticated/project.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/_authenticated/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectIdRoute = AuthenticatedProjectIdRouteImport.update({
  id: '/_authenticated/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/project/$id': typeof AuthenticatedProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/project/$id': typeof AuthenticatedProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/project/$id': typeof AuthenticatedProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/project/$id'
  id:
    '__root__' | '/' | '/_authenticated/studio' | '/_authenticated/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedProjectIdRoute: typeof AuthenticatedProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project/$id': {
      id: '/_authenticated/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AuthenticatedProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedProjectIdRoute: AuthenticatedProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
